language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

sudo: false

matrix:
  fast_finish: true

cache:
  - apt

addons:
  apt:
    packages:
      - nginx-full

install:
  - composer install

script:
  - nginx -h
  - cat /etc/nginx/nginx.conf