language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

sudo: false

matrix:
  fast_finish: true

cache:
  - apt

addons:
  apt:
    packages:
      - nginx
      - realpath
  hosts:
      - localhost
      - test.dev

install:
#  - composer install
  - travis/install-nginx.sh

script:
  - curl -vs 'http://localhost:8080/hello.php' &> /dev/stdout