language: php

php:
    - 5.6

sudo: false

matrix:
  fast_finish: true

cache:
  - apt

addons:
  apt:
    packages:
      - nginx
      - realpath

install:
  - composer install
  - travis/install-nginx.sh

script:
  - curl 'http://localhost/hello.php'